nelmio_cors:
  defaults:
    allow_origin: ['http://localhost:5173']
    allow_methods: ['GET', 'POST', 'DELETE', 'OPTIONS']
    allow_headers: ['Content-Type', 'Authorization']
    max_age: 3600
  paths:
    '^/api/':
      allow_origin: ['http://localhost:5173']
      allow_headers: ['Content-Type', 'Authorization']
      allow_methods: ['GET', 'POST', 'DELETE', 'OPTIONS']
