<?php

// This is a placeholder index.php file
// In a real Symfony application, this would be generated by the Symfony installer

echo '<html><body>';
echo '<h1>Training Booking System</h1>';
echo '<p>Docker environment is working correctly!</p>';
echo '<p>PHP version: ' . phpversion() . '</p>';

// Test MySQL connection
try {
    $dsn = getenv('DATABASE_URL') ?: 'mysql://root:root_password@mysql:3306/training_booking';
    $pdo = new PDO($dsn);
    echo '<p style="color: green;">MySQL connection successful!</p>';
} catch (PDOException $e) {
    echo '<p style="color: red;">MySQL connection failed: ' . $e->getMessage() . '</p>';
}

// Test Redis connection
try {
    $redis = new Redis();
    $redis->connect('redis', 6379);
    echo '<p style="color: green;">Redis connection successful!</p>';
} catch (Exception $e) {
    echo '<p style="color: red;">Redis connection failed: ' . $e->getMessage() . '</p>';
}

echo '</body></html>';