<?php

// This is a placeholder index.php file
// In a real Symfony application, this would be generated by the Symfony installer

echo '<html><body>';
echo '<h1>Training Booking System</h1>';
echo '<p>Docker environment is working correctly!</p>';
echo '<p>PHP version: ' . phpversion() . '</p>';

// Test MySQL connection
try {
    $databaseUrl = getenv('DATABASE_URL') ?: 'mysql://root:root_password@mysql:3306/training_booking';
    $urlComponents = parse_url($databaseUrl);
    $dsn = sprintf(
        'mysql:host=%s;port=%d;dbname=%s',
        $urlComponents['host'],
        $urlComponents['port'] ?? 3306,
        ltrim($urlComponents['path'], '/')
    );
    $username = $urlComponents['user'] ?? null;
    $password = $urlComponents['pass'] ?? null;
    $pdo = new PDO($dsn, $username, $password);
    echo '<p style="color: green;">MySQL connection successful!</p>';
} catch (PDOException $e) {
    error_log('MySQL connection failed: ' . $e->getMessage());
    echo '<p style="color: red;">MySQL connection failed. Please contact the administrator.</p>';
}

// Test Redis connection
try {
    $redis = new Redis();
    $redis->connect('redis', 6379);
    echo '<p style="color: green;">Redis connection successful!</p>';
} catch (Exception $e) {
    echo '<p style="color: red;">Redis connection failed: ' . $e->getMessage() . '</p>';
}

echo '</body></html>';
